### ISSUE TITLE
client running ROS1 melodic and mobot code on kinetic

### ISSUE THREAD

**Issue by imdalaf** [osrf/free_fleet#51]
I am aware that free fleet client requires ROS1 melodic. For a mobot that is running the code on ROS1 kinetic, will that be a problem. If that is, can you provide any advice or suggestion on how to deal with this? Thanks.

**Comment by aaronchongth** [comment]
That is a great question. It has not been tested with a robot running Kinetic, however the main interfaces it uses to work with the ROS 1 navigation stack have been stable for a long time now, so I believe there should not be any issues working with it.

I would however suggest migrating to at least Melodic or even better, Noetic, since it is going to be the last release of ROS 1.

**Comment by imdalaf** [comment]
Thanks @aaronchongth
