### ISSUE TITLE
How to start RMF with free fleet

### ISSUE THREAD

**Issue by Rayman** [osrf/free_fleet#75]
I was able to launch free fleet with both the ros2 server side and the ros1 client side:
```sh
ros2 launch ff_examples_ros2 turtlebot3_world_ff.launch.xml
roslaunch ff_examples_ros1 turtlebot3_world_ff.launch
```
But how do I start RMF with this? Is there a specific launch file with a configuration for the turtlebot world?

**Comment by aaronchongth** [comment]
Hello @Rayman!

There are some further setup required to use free fleet with RMF, you would need

* a navigation graph generated using `traffic_editor` and `building_map_tools`, example [here](https://github.com/osrf/rmf_demos/tree/master/rmf_demo_maps/maps/office) 
* to configure a fleet adapter with the parameters of the robot fleet, example [here](https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/adapters/tinyRobot_adapter.launch.xml), providing it with the navigation graph generated previously

There is currently no working example in simulation that integrates free fleet with RMF at the moment, due to the simulated robots running ROS 1 while all plugins developed for RMF use ROS 2 (doors, lifts, humans, etc).

However we have been using this setup for physical robots. The interaction between free fleet and the RMF fleet adapter is in ROS 2 topics, linked [here](https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/src/full_control/main.cpp#L416-L426), which the free fleet server publishes and subscribes to.

**Comment by Rayman** [comment]
Thanks for the pointers!

**Comment by edcogue** [comment]
I'm trying to connect also RMF and Free Fleet. Is the tinyRobotAdapter ready to use in simulation or needs some development? 
Also I have a navigation graph developed but I don't know how to launch the adapter. Is as simple as launch the launchfile passing navigation graph_file to make things work?

**Comment by aaronchongth** [comment]
Hello @edcogue!

> I'm trying to connect also RMF and Free Fleet. Is the tinyRobotAdapter ready to use in simulation or needs some development?

The `tinyRobotAdapter` can be used in simulation at the moment with the `slotcar` plugin, but not Free Fleet.

> Also I have a navigation graph developed but I don't know how to launch the adapter. Is as simple as launch the launchfile passing navigation graph_file to make things work?

We have some examples on how to launch a fleet adapter with a navigation graph here, https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos/launch/hotel.launch.xml#L46-L60

**Comment by RDaneelOlivav** [comment]
Hi!
I managed to have a simulation working with Nav2 and Freefleet server.
Also to have the RMF working with its map and everything needed for RMF to work.

But is there a way to connect the Free Fleet with the RMF? It doesn't seem to find the robots available for planning.
I tested and it works if I use the sltcar plugin, but I want the robots to use the navigation stack.

Do I have to implement a bridge between the FF-Server and the `rmf_task_dispatcher`?

Any insights on this?

**Comment by frkngltk** [comment]
Hello @RDaneelOlivav,

Is there any progress on this situation? Is there an application or method that you could provide a solution for?

**Comment by alperen-keser** [comment]
Hi @RDaneelOlivav. 

I am also working on the same application. Any progress?

**Comment by tomkimsour** [comment]
I'm also interested in this
